### ISSUE TITLE
Potential bug - libbiosig fails to compile with homebrew, OS X 10.11

### ISSUE THREAD

**Issue by schillm** [schloegl/homebrew-biosig#1]
Hi,

I attempted to install libbiosig via homebrew.  I run Octave 4.0.0 on OS X 10.11.4, Core 2 Duo 8 GB RAM.  I have already installed biosig within the Octave environment.  I manually installed all of libbiosig's dependencies.

When I run:

```
brew tap schloegl/biosig
brew install libbiosig
```

I get the error:
`Error: Empty installation`

brew --config output:

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 39da42bacb746d323e00ce5e293fc0463db7baf0
Last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penny
OS X: 10.11.4-x86_64
Xcode: 7.3
CLT: 7.3.0.0.1.1457485338
Clang: 7.3 build 703
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p648
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_51
```

brew doctor output:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected delis:
    /usr/local/lib/libbiosig.1.7.7.dylib
    /usr/local/lib/libbiosig2.1.7.7.dylib
    /usr/local/lib/libgdftime.dylib
    /usr/local/lib/libphysicalunits.dylib
    /usr/local/lib/libtcl8.6.dylib
    /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/biosig-dev.h
    /usr/local/include/biosig.h
    /usr/local/include/biosig2.h
    /usr/local/include/fakemysql.h
    /usr/local/include/fakepq.h
    /usr/local/include/fakesql.h
    /usr/local/include/gdftime.h
    /usr/local/include/itcl.h
    /usr/local/include/itcl2TclOO.h
    /usr/local/include/itclDecls.h
    /usr/local/include/itclInt.h
    /usr/local/include/itclIntDecls.h
    /usr/local/include/itclMigrate2TclCore.h
    /usr/local/include/itclTclIntStubsFcn.h
    /usr/local/include/mysqlStubs.h
    /usr/local/include/odbcStubs.h
    /usr/local/include/physicalunits.h
    /usr/local/include/pqStubs.h
    /usr/local/include/tcl.h
    /usr/local/include/tclDecls.h
    /usr/local/include/tclOO.h
    /usr/local/include/tclOODecls.h
    /usr/local/include/tclPlatDecls.h
    /usr/local/include/tclThread.h
    /usr/local/include/tclTomMath.h
    /usr/local/include/tclTomMathDecls.h
    /usr/local/include/tdbc.h
    /usr/local/include/tdbcDecls.h
    /usr/local/include/tdbcInt.h
    /usr/local/include/tk.h
    /usr/local/include/tkDecls.h
    /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/libbiosig.pc
    /usr/local/lib/pkgconfig/tcl.pc
    /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libbiosig.a
    /usr/local/lib/libbiosig2.a
    /usr/local/lib/libgdftime.a
    /usr/local/lib/libphysicalunits.a
    /usr/local/lib/libtclstub8.6.a
    /usr/local/lib/libtkstub8.6.a
```

Thanks for taking a look!
Matt

**Comment by cbrnr** [comment]
@schillm can you try if it works with the latest version? I think this issue should be fixed.

**Comment by schloegl** [comment]
This issue should be solved now. Please run

  brew update 
  brew tap schloegl/biosig
  brew install libbiosig

and test this.

**Comment by yueqiw** [comment]
Hi,

I'm getting the same error with the latest version: 
```
==> PREFIX=$HOMEBREW_PREFIX  make
==> PREFIX=$HOMEBREW_CELLAR/libbiosig/1.8.4/ make install
Error: Empty installation
```

```
brew  --config

HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 29070ad89d76776089e8360e9d453b47fc4479fb
Core tap last commit: 3 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/yueqi/anaconda/bin/python => /Users/yueqi/anaconda/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
MacPorts/Fink: /opt/local/bin/port
```

Thanks!

**Comment by cbrnr** [comment]
I can confirm that this bug still exists with the latest version. I think it's likely due to the wrong version number in line 28 of `libbiosig.rb`, which currently reads:

    system "PREFIX=$HOMEBREW_CELLAR/libbiosig/1.8.4/ make install"

I think it should be changed to

    system "PREFIX=$HOMEBREW_CELLAR/libbiosig/1.8.4b/ make install"

**Comment by schloegl** [comment]
iibbiosig for homebrew is upgraded to v1.8.4c, which seems to solve the compilation problem. 
However, it seems that the include files are not properly installed, they are only in cellar but no links in /usr/local/include/

**Comment by cbrnr** [comment]
Yes, I can confirm that the error is gone and that there are no symlinks in `/usr/local/include`, but interestingly the libraries are present in `/usr/local/lib`.

**Comment by schloegl** [comment]
This issue should be solved with the update to libbiosig 1.9.0, its using autoconf's prefix which should do the right thing.
